version: '3.8'

services:
  bwwc-backend:
    container_name: bwwc-backend
    restart: always
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=development
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:7.0-alpine
    container_name: "redis"
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    container_name: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  postgres:
    image: postgres:13.3-alpine
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres