version: '3.8'

services:
  bwwc-backend:
    container_name: bwwc-backend
    restart: always
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=development
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:7.0-alpine
    container_name: "redis"
    ports:
      - "6379:6379"
