# Deployment of the backend and frontend for the staging environment
# Deployed on NERC 1 Server
# Deployed at https://mpc.sail.codes
version: '3.8'
services:
  bwwc-backend:
    container_name: bwwc-backend-staging
    restart: always
    image: multiparty/bwwc-backend:main
    ports:
      - 8000:8000
    depends_on:
    - bwwc-redis
    env_file:
    - ../stack.env
  bwwc-redis:
    restart: always
    image: redis:7.0-alpine
    container_name: bwwc-redis-staging
    command: redis-server --appendonly yes --replica-read-only no
    environment:
      - redis_read_only=0
    ports:
    - 6379:6379
    volumes:
      - bwwc_data:/data
  bwwc-frontend:
    container_name: bwwc-frontend
    restart: always
    image: multiparty/bwwc-client:main
    ports:
    - 3008:80
    env_file:
    - ../stack.env
  bwwc-mongo:
    container_name: bwwc-mongo
    restart: always
    image: mongo
    ports:
      - 27025:27017
    volumes:
      - bwwc_data:/data/db
    env_file:
      - ../stack.env
  bwwc-postgres:
    container_name: bwwc-postgres
    restart: always
    image: postgres:13.3-alpine
    ports:
      - 5500:5432
    volumes:
      - bwwc_data:/var/lib/postgresql/data

volumes:
  bwwc_data: ~