# Deployment of the backend and frontend for the staging environment
# Deployed on webmpc-production Server
# Deployed at https://100talent.org
version: '3.8'
services:
  bwwc-backend:
    container_name: bwwc-backend
    restart: always
    image: multiparty/bwwc-backend:latest
    ports:
      - 8000:8000
    depends_on:
      - bwwc-redis
    env_file:
      - ../stack.env
  bwwc-redis:
    restart: always
    image: redis:7.0-alpine
    container_name: bwwc-redis
    command: redis-server --appendonly yes --replica-read-only no
    ports:
      - 6379:6379
    volumes:
      - bwwc_data_production:/data
  bwwc-frontend:
    container_name: bwwc-frontend
    restart: always
    image: multiparty/bwwc-client:latest
    ports:
      - 80:80
    env_file:
      - ../stack.env
  bwwc-mongo:
    container_name: bwwc-mongo
    restart: always
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - bwwc_data_production:/data/db
    env_file:
      - ../stack.env

volumes:
  bwwc_data_production: ~