# Deployment of the backend and frontend for the staging environment
# Deployed on webmpc-production Server
# Deployed at https://100talent.org
version: '3.8'
services:
  bwwc-backend:
    container_name: bwwc-backend
    restart: always
    image: multiparty/bwwc-backend:latest
    ports:
      - 8000:8000

    env_file:
      - ../stack.env
  bwwc-frontend:
    container_name: bwwc-frontend
    restart: always
    image: multiparty/bwwc-client:latest
    ports:
      - 80:80
    env_file:
      - ../stack.env
  bwwc-mongo:
    container_name: bwwc-mongo
    restart: always
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - bwwc_data_production:/data/db
    env_file:
      - ../stack.env

volumes:
  bwwc_data_production: ~