name: backend
on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest isort black
    - name: Run pytest
      run: pytest
    - name: Check isort
      run: isort --check-only .
    - name: Check black
      run: black --check .

